<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<style>
body {
    font-family: DejaVu Sans;
    padding: 20px;
    color: #333;
}

/* HEADER */
.header {
    text-align: center;
    margin-bottom: 20px;
}

.header h1 {
    color: #4f46e5;
    margin-bottom: 5px;
}

.header p {
    color: gray;
    font-size: 12px;
}

/* STATS */
.stats {
    width: 100%;
    margin-bottom: 20px;
}

.stats td {
    width: 33%;
    padding: 10px;
}

.card {
    border: 1px solid #ddd;
    padding: 15px;
    text-align: center;
    border-radius: 8px;
}

.card h2 {
    color: #4f46e5;
    margin-top: 5px;
}

/* TABLE */
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
}

th {
    background: #4f46e5;
    color: white;
    padding: 10px;
}

td {
    border: 1px solid #ddd;
    padding: 10px;
    text-align: center;
}

/* FOOTER */
.footer {
    margin-top: 30px;
    text-align: center;
    font-size: 12px;
    color: gray;
}
</style>

</head>

<body>

<!-- HEADER -->
<table width="100%" style="margin-bottom:20px;">
<tr>
    <td width="20%">
        <img src="{{ public_path('logo.png') }}" width="60">
    </td>

    <td width="80%" style="text-align:right;">
        <h2 style="margin:0; color:#4f46e5;">{{ $pharmacy }}</h2>
        <p style="margin:0;">{{ date('d/m/Y') }}</p>
    </td>
</tr>
</table>

<hr>

<!-- STATS -->
<table class="stats">
<tr>
    <td>
        <div class="card">
            <p>Total Revenue</p>
            <h2>{{ $revenue }} DH</h2>
        </div>
    </td>

    <td>
        <div class="card">
            <p>Total Ventes</p>
            <h2>{{ $ventes }}</h2>
        </div>
    </td>

    <td>
        <div class="card">
            <p>Low Stock</p>
            <h2>{{ count($lowStock) }}</h2>
        </div>
    </td>
</tr>
</table>

<!-- TABLE -->
<h3>⚠️ Low Stock Medicaments</h3>

<table>
<thead>
<tr>
    <th>Nom</th>
    <th>Quantité</th>
    <th>Expiration</th>
</tr>
</thead>

<tbody>
@foreach($lowStock as $m)
<tr>
    <td>{{ $m->nom }}</td>
    <td>{{ $m->quantite }}</td>
    <td>{{ $m->date_expiration }}</td>
</tr>
@endforeach
</tbody>
</table>

<!-- FOOTER -->
<div class="footer">
    Generated by PharmaSys © {{ date('Y') }}
</div>

</body>
</html>