<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<style>
body {
    font-family: DejaVu Sans;
    padding: 20px;
    color: #333;
}

.period {
    margin: 18px 0;
    padding: 12px 16px;
    border: 1px solid #ddd;
    border-left: 4px solid #4f46e5;
    background: #f8fafc;
}

.period .label {
    color: #666;
    font-size: 12px;
    margin: 0 0 4px 0;
}

.period .value {
    color: #111827;
    font-size: 15px;
    font-weight: bold;
    margin: 0;
}

.stats {
    width: 100%;
    margin-bottom: 20px;
}

.stats td {
    width: 50%;
    padding: 10px;
}

.card {
    border: 1px solid #ddd;
    padding: 15px;
    text-align: center;
    border-radius: 8px;
}

.card h2 {
    color: #4f46e5;
    margin-top: 5px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
}

th {
    background: #4f46e5;
    color: white;
    padding: 10px;
}

td {
    border: 1px solid #ddd;
    padding: 9px;
    text-align: center;
    font-size: 12px;
}

.details {
    text-align: left;
}

.footer {
    margin-top: 30px;
    text-align: center;
    font-size: 12px;
    color: gray;
}
</style>

</head>

<body>

<table width="100%" style="margin-bottom:20px;">
<tr>
    <td width="20%">
        <img src="{{ public_path('logo.png') }}" width="60">
    </td>

    <td width="80%" style="text-align:right;">
        <h2 style="margin:0; color:#4f46e5;">{{ $pharmacy }}</h2>
        <p style="margin:0;">{{ date('d/m/Y') }}</p>
    </td>
</tr>
</table>

<hr>

<div class="period">
    <p class="label">Utilisateur</p>
    <p class="value">{{ $userName ?: 'Tous les utilisateurs' }}</p>
</div>

<div class="period">
    <p class="label">Periode du rapport</p>
    <p class="value">
        @if(!empty($startDate) && !empty($endDate))
            Du {{ $startDate }} au {{ $endDate }}
        @else
            {{ $periodLabel }}
        @endif
    </p>
</div>

<table class="stats">
<tr>
    <td>
        <div class="card">
            <p>Total Revenue</p>
            <h2>{{ $totalRevenue }} DH</h2>
        </div>
    </td>

    <td>
        <div class="card">
            <p>Total Ventes</p>
            <h2>{{ $totalVentes }}</h2>
        </div>
    </td>
</tr>
</table>

<h3>Historique des ventes</h3>

<table>
<thead>
<tr>
    <th>ID</th>
    <th>Date</th>
    <th>Utilisateur</th>
    <th>Total</th>
    <th>Details</th>
</tr>
</thead>

<tbody>
@forelse($ventes as $vente)
<tr>
    <td>#{{ $vente->id }}</td>
    <td>{{ optional($vente->created_at)->format('Y-m-d H:i') }}</td>
    <td>{{ optional($vente->user)->name ?? 'Unknown' }}</td>
    <td>{{ $vente->total }} DH</td>
    <td class="details">
        @foreach($vente->details as $detail)
            {{ optional($detail->medicament)->nom }} x {{ $detail->quantite }}<br>
        @endforeach
    </td>
</tr>
@empty
<tr>
    <td colspan="5">Aucune vente trouvee.</td>
</tr>
@endforelse
</tbody>
</table>

<div class="footer">
    Generated by PharmaSys (c) {{ date('Y') }}
</div>

</body>
</html>
